### ISSUE TITLE
error msg when using 'get pdf of whole set' command

### ISSUE THREAD

**Issue by benrosow** [owen-kellie-smith/chart3#8]
from php my info, I am using version 8.0.12.  I get the below error when I try to generate a pdf using the 'get pdf from whole set' command.

Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_runtime() in C:\xampp\htdocs\Chart3TSB\vendor\setasign\fpdf\fpdf.php:1043 Stack trace: #0 C:\xampp\htdocs\Chart3TSB\vendor\setasign\fpdf\fpdf.php(77): FPDF->_dochecks() #1 C:\xampp\htdocs\Chart3TSB\Gig.php(1090): FPDF->__construct() #2 C:\xampp\htdocs\Chart3TSB\Gig.php(999): Gig->pdfFromGigExplicit(Array, 'C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\Chart3TSB\index.php(114): Gig->pdfFromGig(Array) #4 {main} thrown in C:\xampp\htdocs\Chart3TSB\vendor\setasign\fpdf\fpdf.php on line 1043

**Comment by benrosow** [comment]
Thanks, BTW.

**Comment by owen-kellie-smith** [comment]
Hi Ben, I've wrapped up the two lines 1043 and 1044 in an 
```
if (function_exists('get_magic_quotes_runtime'){
...
}

```
expression, which has done no harm for me on PHP 7.3.30.

An alternative is to comment out lines 1043 to 1044 i.e. change ...chart3/vendor/setasign/fpdf/fpdf.php from
```
	if(get_magic_quotes_runtime())
		@set_magic_quotes_runtime(0);
```

to
```
//	if(get_magic_quotes_runtime())
//		@set_magic_quotes_runtime(0);


```

**Comment by owen-kellie-smith** [comment]
The related commit is f03c0aa6d189bce06cb9bdf1dab7e59d82805da3.
